apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  labels:
    app: dotnet
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
        env: dev
    spec:
      containers:
      - name: dotnet
        image: cloudaccelerator.azurecr.io/myapp_dotnet
        ports:
        - name:  http
          containerPort: 3000
          protocol: TCP